//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuance_request
    {
        public int is_id { get; set; }
        public int warehouse_id { get; set; }
        public Nullable<System.DateTime> is_date { get; set; }
        public int client_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual client client { get; set; }
        public virtual Item Item { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
