//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply_request
    {
        public int srequest_id { get; set; }
        public int warehouse_id { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
